name: moviex
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  connectivity_plus: ^2.3.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_analytics: ^9.1.12
  firebase_core: ^1.19.1
  firebase_crashlytics: ^2.8.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  get_storage: ^2.0.3
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  http: ^0.13.4
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  path_provider: ^2.0.11
  skeletons: ^0.0.3
dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  http_mock_adapter: ^0.3.3
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  mockito: ^5.2.0
  test: ^1.21.1
flutter:
  uses-material-design: true
  assets:
    - certificates/
  #   - images/a_dot_ham.jpeg
